//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GXP.Core {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class GXPSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static GXPSetting defaultInstance = ((GXPSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GXPSetting())));
        
        public static GXPSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("iframe,script,src=,document.getelementbyid")]
        public string IsValidHTMLElement {
            get {
                return ((string)(this["IsValidHTMLElement"]));
            }
            set {
                this["IsValidHTMLElement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int RSSCacheDuration {
            get {
                return ((int)(this["RSSCacheDuration"]));
            }
            set {
                this["RSSCacheDuration"] = value;
            }
        }
    }
}
