//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GXP.Core.ExternalServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Deal", Namespace="http://schemas.datacontract.org/2004/07/DMS.Business")]
    [System.SerializableAttribute()]
    public partial class Deal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DealResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DealResultLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GXP.Core.ExternalServices.DealTypeType DealTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExpiryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GXP.Core.ExternalServices.DealGroup GroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsStaticField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LiveSearchAllowedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifydateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GXP.Core.ExternalServices.DealQueryParam[] QueryParamsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RefreshRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ResultColumnsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] SortColumnsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SortDescendingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StaticLiveSearchAllowedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] TargetValueListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TargetValuesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Createdate {
            get {
                return this.CreatedateField;
            }
            set {
                if ((this.CreatedateField.Equals(value) != true)) {
                    this.CreatedateField = value;
                    this.RaisePropertyChanged("Createdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DealResult {
            get {
                return this.DealResultField;
            }
            set {
                if ((object.ReferenceEquals(this.DealResultField, value) != true)) {
                    this.DealResultField = value;
                    this.RaisePropertyChanged("DealResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DealResultLimit {
            get {
                return this.DealResultLimitField;
            }
            set {
                if ((this.DealResultLimitField.Equals(value) != true)) {
                    this.DealResultLimitField = value;
                    this.RaisePropertyChanged("DealResultLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GXP.Core.ExternalServices.DealTypeType DealType {
            get {
                return this.DealTypeField;
            }
            set {
                if ((this.DealTypeField.Equals(value) != true)) {
                    this.DealTypeField = value;
                    this.RaisePropertyChanged("DealType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpiryDate {
            get {
                return this.ExpiryDateField;
            }
            set {
                if ((this.ExpiryDateField.Equals(value) != true)) {
                    this.ExpiryDateField = value;
                    this.RaisePropertyChanged("ExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GXP.Core.ExternalServices.DealGroup Group {
            get {
                return this.GroupField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupField, value) != true)) {
                    this.GroupField = value;
                    this.RaisePropertyChanged("Group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsStatic {
            get {
                return this.IsStaticField;
            }
            set {
                if ((this.IsStaticField.Equals(value) != true)) {
                    this.IsStaticField = value;
                    this.RaisePropertyChanged("IsStatic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LiveSearchAllowed {
            get {
                return this.LiveSearchAllowedField;
            }
            set {
                if ((this.LiveSearchAllowedField.Equals(value) != true)) {
                    this.LiveSearchAllowedField = value;
                    this.RaisePropertyChanged("LiveSearchAllowed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy {
            get {
                return this.ModifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedByField, value) != true)) {
                    this.ModifiedByField = value;
                    this.RaisePropertyChanged("ModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Modifydate {
            get {
                return this.ModifydateField;
            }
            set {
                if ((this.ModifydateField.Equals(value) != true)) {
                    this.ModifydateField = value;
                    this.RaisePropertyChanged("Modifydate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GXP.Core.ExternalServices.DealQueryParam[] QueryParams {
            get {
                return this.QueryParamsField;
            }
            set {
                if ((object.ReferenceEquals(this.QueryParamsField, value) != true)) {
                    this.QueryParamsField = value;
                    this.RaisePropertyChanged("QueryParams");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RefreshRate {
            get {
                return this.RefreshRateField;
            }
            set {
                if ((this.RefreshRateField.Equals(value) != true)) {
                    this.RefreshRateField = value;
                    this.RaisePropertyChanged("RefreshRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ResultColumns {
            get {
                return this.ResultColumnsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultColumnsField, value) != true)) {
                    this.ResultColumnsField = value;
                    this.RaisePropertyChanged("ResultColumns");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] SortColumns {
            get {
                return this.SortColumnsField;
            }
            set {
                if ((object.ReferenceEquals(this.SortColumnsField, value) != true)) {
                    this.SortColumnsField = value;
                    this.RaisePropertyChanged("SortColumns");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SortDescending {
            get {
                return this.SortDescendingField;
            }
            set {
                if ((this.SortDescendingField.Equals(value) != true)) {
                    this.SortDescendingField = value;
                    this.RaisePropertyChanged("SortDescending");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool StaticLiveSearchAllowed {
            get {
                return this.StaticLiveSearchAllowedField;
            }
            set {
                if ((this.StaticLiveSearchAllowedField.Equals(value) != true)) {
                    this.StaticLiveSearchAllowedField = value;
                    this.RaisePropertyChanged("StaticLiveSearchAllowed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] TargetValueList {
            get {
                return this.TargetValueListField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetValueListField, value) != true)) {
                    this.TargetValueListField = value;
                    this.RaisePropertyChanged("TargetValueList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TargetValues {
            get {
                return this.TargetValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetValuesField, value) != true)) {
                    this.TargetValuesField = value;
                    this.RaisePropertyChanged("TargetValues");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DealGroup", Namespace="http://schemas.datacontract.org/2004/07/DMS.Business")]
    [System.SerializableAttribute()]
    public partial class DealGroup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateModifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GXP.Core.ExternalServices.DealDefinition[] DealDefinitionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateModified {
            get {
                return this.DateModifiedField;
            }
            set {
                if ((this.DateModifiedField.Equals(value) != true)) {
                    this.DateModifiedField = value;
                    this.RaisePropertyChanged("DateModified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GXP.Core.ExternalServices.DealDefinition[] DealDefinitions {
            get {
                return this.DealDefinitionsField;
            }
            set {
                if ((object.ReferenceEquals(this.DealDefinitionsField, value) != true)) {
                    this.DealDefinitionsField = value;
                    this.RaisePropertyChanged("DealDefinitions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName {
            get {
                return this.GroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNameField, value) != true)) {
                    this.GroupNameField = value;
                    this.RaisePropertyChanged("GroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy {
            get {
                return this.ModifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedByField, value) != true)) {
                    this.ModifiedByField = value;
                    this.RaisePropertyChanged("ModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DealTypeType", Namespace="http://schemas.datacontract.org/2004/07/DMS.Business")]
    public enum DealTypeType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Air = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hotel = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Car = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Vacation = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DealQueryParam", Namespace="http://schemas.datacontract.org/2004/07/DMS.Business")]
    [System.SerializableAttribute()]
    public partial class DealQueryParam : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConjunctionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GXP.Core.ExternalServices.OperatorType OperatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TargetValue1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TargetValue2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Conjunction {
            get {
                return this.ConjunctionField;
            }
            set {
                if ((object.ReferenceEquals(this.ConjunctionField, value) != true)) {
                    this.ConjunctionField = value;
                    this.RaisePropertyChanged("Conjunction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataType {
            get {
                return this.DataTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DataTypeField, value) != true)) {
                    this.DataTypeField = value;
                    this.RaisePropertyChanged("DataType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldName {
            get {
                return this.FieldNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldNameField, value) != true)) {
                    this.FieldNameField = value;
                    this.RaisePropertyChanged("FieldName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GXP.Core.ExternalServices.OperatorType Operator {
            get {
                return this.OperatorField;
            }
            set {
                if ((this.OperatorField.Equals(value) != true)) {
                    this.OperatorField = value;
                    this.RaisePropertyChanged("Operator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TargetValue1 {
            get {
                return this.TargetValue1Field;
            }
            set {
                if ((object.ReferenceEquals(this.TargetValue1Field, value) != true)) {
                    this.TargetValue1Field = value;
                    this.RaisePropertyChanged("TargetValue1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TargetValue2 {
            get {
                return this.TargetValue2Field;
            }
            set {
                if ((object.ReferenceEquals(this.TargetValue2Field, value) != true)) {
                    this.TargetValue2Field = value;
                    this.RaisePropertyChanged("TargetValue2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DealDefinition", Namespace="http://schemas.datacontract.org/2004/07/DMS.Business")]
    [System.SerializableAttribute()]
    public partial class DealDefinition : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GXP.Core.ExternalServices.AirDealDetail[] AirDealDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GXP.Core.ExternalServices.DealGroup DealGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid DealIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DealNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte DealTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Xml.Linq.XElement DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ExpiryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> GroupIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsStaticField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RefreshRateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GXP.Core.ExternalServices.AirDealDetail[] AirDealDetails {
            get {
                return this.AirDealDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.AirDealDetailsField, value) != true)) {
                    this.AirDealDetailsField = value;
                    this.RaisePropertyChanged("AirDealDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GXP.Core.ExternalServices.DealGroup DealGroup {
            get {
                return this.DealGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.DealGroupField, value) != true)) {
                    this.DealGroupField = value;
                    this.RaisePropertyChanged("DealGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DealID {
            get {
                return this.DealIDField;
            }
            set {
                if ((this.DealIDField.Equals(value) != true)) {
                    this.DealIDField = value;
                    this.RaisePropertyChanged("DealID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DealName {
            get {
                return this.DealNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DealNameField, value) != true)) {
                    this.DealNameField = value;
                    this.RaisePropertyChanged("DealName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte DealType {
            get {
                return this.DealTypeField;
            }
            set {
                if ((this.DealTypeField.Equals(value) != true)) {
                    this.DealTypeField = value;
                    this.RaisePropertyChanged("DealType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Xml.Linq.XElement Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ExpiryDate {
            get {
                return this.ExpiryDateField;
            }
            set {
                if ((this.ExpiryDateField.Equals(value) != true)) {
                    this.ExpiryDateField = value;
                    this.RaisePropertyChanged("ExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> GroupID {
            get {
                return this.GroupIDField;
            }
            set {
                if ((this.GroupIDField.Equals(value) != true)) {
                    this.GroupIDField = value;
                    this.RaisePropertyChanged("GroupID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsStatic {
            get {
                return this.IsStaticField;
            }
            set {
                if ((this.IsStaticField.Equals(value) != true)) {
                    this.IsStaticField = value;
                    this.RaisePropertyChanged("IsStatic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy {
            get {
                return this.ModifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedByField, value) != true)) {
                    this.ModifiedByField = value;
                    this.RaisePropertyChanged("ModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RefreshRate {
            get {
                return this.RefreshRateField;
            }
            set {
                if ((this.RefreshRateField.Equals(value) != true)) {
                    this.RefreshRateField = value;
                    this.RaisePropertyChanged("RefreshRate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AirDealDetail", Namespace="http://schemas.datacontract.org/2004/07/DMS.Business")]
    [System.SerializableAttribute()]
    public partial class AirDealDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Xml.Linq.XElement CustomizerXmlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GXP.Core.ExternalServices.DealDefinition DealDefinitionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DealIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Xml.Linq.XElement FilterXmlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QueryParamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Xml.Linq.XElement QueryParamXMLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Xml.Linq.XElement CustomizerXml {
            get {
                return this.CustomizerXmlField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomizerXmlField, value) != true)) {
                    this.CustomizerXmlField = value;
                    this.RaisePropertyChanged("CustomizerXml");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GXP.Core.ExternalServices.DealDefinition DealDefinition {
            get {
                return this.DealDefinitionField;
            }
            set {
                if ((object.ReferenceEquals(this.DealDefinitionField, value) != true)) {
                    this.DealDefinitionField = value;
                    this.RaisePropertyChanged("DealDefinition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DealID {
            get {
                return this.DealIDField;
            }
            set {
                if ((this.DealIDField.Equals(value) != true)) {
                    this.DealIDField = value;
                    this.RaisePropertyChanged("DealID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Xml.Linq.XElement FilterXml {
            get {
                return this.FilterXmlField;
            }
            set {
                if ((object.ReferenceEquals(this.FilterXmlField, value) != true)) {
                    this.FilterXmlField = value;
                    this.RaisePropertyChanged("FilterXml");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QueryParam {
            get {
                return this.QueryParamField;
            }
            set {
                if ((object.ReferenceEquals(this.QueryParamField, value) != true)) {
                    this.QueryParamField = value;
                    this.RaisePropertyChanged("QueryParam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Xml.Linq.XElement QueryParamXML {
            get {
                return this.QueryParamXMLField;
            }
            set {
                if ((object.ReferenceEquals(this.QueryParamXMLField, value) != true)) {
                    this.QueryParamXMLField = value;
                    this.RaisePropertyChanged("QueryParamXML");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperatorType", Namespace="http://schemas.datacontract.org/2004/07/DMS.Business")]
    public enum OperatorType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Equal = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotEqual = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GreaterThan = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LessThan = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GreaterThanEqualTo = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LessThanEqualTo = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Contains = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExternalServices.IDealService")]
    public interface IDealService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDealService/GetDealResult", ReplyAction="http://tempuri.org/IDealService/GetDealResultResponse")]
        string GetDealResult(string DealName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDealService/GetDealResultWithParam", ReplyAction="http://tempuri.org/IDealService/GetDealResultWithParamResponse")]
        string GetDealResultWithParam(string DealName, string Parameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDealService/GetActiveDeals", ReplyAction="http://tempuri.org/IDealService/GetActiveDealsResponse")]
        GXP.Core.ExternalServices.Deal[] GetActiveDeals(string GroupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDealService/GetExpiredDeals", ReplyAction="http://tempuri.org/IDealService/GetExpiredDealsResponse")]
        GXP.Core.ExternalServices.Deal[] GetExpiredDeals(string GroupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDealService/GetAllDeals", ReplyAction="http://tempuri.org/IDealService/GetAllDealsResponse")]
        GXP.Core.ExternalServices.Deal[] GetAllDeals();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDealService/RemoveDealCache", ReplyAction="http://tempuri.org/IDealService/RemoveDealCacheResponse")]
        void RemoveDealCache(System.Guid DealID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDealService/CreateDealCache", ReplyAction="http://tempuri.org/IDealService/CreateDealCacheResponse")]
        void CreateDealCache(System.Guid DealID, string parameter, string Result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDealService/DeleteDeal", ReplyAction="http://tempuri.org/IDealService/DeleteDealResponse")]
        bool DeleteDeal(System.Guid DealID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDealService/GetDealResultHistory", ReplyAction="http://tempuri.org/IDealService/GetDealResultHistoryResponse")]
        string GetDealResultHistory(System.Guid DealID, System.DateTime target);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDealService/GetAllRecFromCacheObject", ReplyAction="http://tempuri.org/IDealService/GetAllRecFromCacheObjectResponse")]
        string[] GetAllRecFromCacheObject();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDealService/RemoveFromCacheObject", ReplyAction="http://tempuri.org/IDealService/RemoveFromCacheObjectResponse")]
        void RemoveFromCacheObject(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDealService/GetMemCachedServerStats", ReplyAction="http://tempuri.org/IDealService/GetMemCachedServerStatsResponse")]
        string GetMemCachedServerStats();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDealServiceChannel : GXP.Core.ExternalServices.IDealService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DealServiceClient : System.ServiceModel.ClientBase<GXP.Core.ExternalServices.IDealService>, GXP.Core.ExternalServices.IDealService {
        
        public DealServiceClient() {
        }
        
        public DealServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DealServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DealServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DealServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDealResult(string DealName) {
            return base.Channel.GetDealResult(DealName);
        }
        
        public string GetDealResultWithParam(string DealName, string Parameter) {
            return base.Channel.GetDealResultWithParam(DealName, Parameter);
        }
        
        public GXP.Core.ExternalServices.Deal[] GetActiveDeals(string GroupName) {
            return base.Channel.GetActiveDeals(GroupName);
        }
        
        public GXP.Core.ExternalServices.Deal[] GetExpiredDeals(string GroupName) {
            return base.Channel.GetExpiredDeals(GroupName);
        }
        
        public GXP.Core.ExternalServices.Deal[] GetAllDeals() {
            return base.Channel.GetAllDeals();
        }
        
        public void RemoveDealCache(System.Guid DealID) {
            base.Channel.RemoveDealCache(DealID);
        }
        
        public void CreateDealCache(System.Guid DealID, string parameter, string Result) {
            base.Channel.CreateDealCache(DealID, parameter, Result);
        }
        
        public bool DeleteDeal(System.Guid DealID) {
            return base.Channel.DeleteDeal(DealID);
        }
        
        public string GetDealResultHistory(System.Guid DealID, System.DateTime target) {
            return base.Channel.GetDealResultHistory(DealID, target);
        }
        
        public string[] GetAllRecFromCacheObject() {
            return base.Channel.GetAllRecFromCacheObject();
        }
        
        public void RemoveFromCacheObject(string key) {
            base.Channel.RemoveFromCacheObject(key);
        }
        
        public string GetMemCachedServerStats() {
            return base.Channel.GetMemCachedServerStats();
        }
    }
}
